# Generated by Django 5.2.6 on 2025-09-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripplan',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='tripplan',
            name='cycle_used_hours',
        ),
        migrations.RemoveField(
            model_name='tripplan',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='tripplan',
            name='pickup_location',
        ),
        migrations.AddField(
            model_name='tripplan',
            name='co_driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='current_cycle_used',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='driver_name',
            field=models.CharField(default='Unknown Driver', max_length=100),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='plan_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='start_date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='trailer_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='truck_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
